In [1]:
import numpy as np

In [2]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.random.randn(3,3)

array([[ 0.31141142, -0.62247506,  0.29604164],
       [ 1.14496174, -0.32629915,  0.00848419],
       [ 1.73376969,  0.34041318,  1.00809135]])

In [15]:
np.random.randn(3,3)

array([[ 0.04090784, -0.26996195, -1.03281428],
       [ 0.19639727, -1.10143837,  1.42334233],
       [-0.61730597,  0.05290255,  0.47817545]])

In [13]:
np.random.randint(0,100,5)

array([20, 80, 58, 33, 25])

In [19]:
np.random.seed(50)
print(np.random.randn(3,3))
np.random.seed(50)
print(np.random.randn(3,3))

[[-1.56035211 -0.0309776  -0.62092842]
 [-1.46458049  1.41194612 -0.47673214]
 [-0.78046921  1.07026774 -1.2822926 ]]
[[-1.56035211 -0.0309776  -0.62092842]
 [-1.46458049  1.41194612 -0.47673214]
 [-0.78046921  1.07026774 -1.2822926 ]]
